import {
  Home,
  Car,
  UtensilsCrossed,
  ShoppingCart,
  ShoppingBag,
  HeartPulse,
  Repeat,
  PiggyBank,
  Wallet,
  Banknote,
  CreditCard,
  Landmark,
  Coins,
  Gift,
  Plane,
  GraduationCap,
  Briefcase,
  Dumbbell,
  Gamepad2,
  Film,
  Target,
  TrendingUp,
  TrendingDown,
  LineChart,
  Zap,
  MoreHorizontal,
  BookOpen,
  Baby,
  Dog,
  Wrench,
  Fuel,
  Phone,
  Wifi,
  Umbrella,
  Star,
  Shield,
  Receipt,
  Shirt,
  Coffee,
  Pill,
  Bus,
  Train,
  Bike,
  Building2,
  Trees,
  Music,
  Camera,
  Scissors,
  Droplet,
  Flame,
  Sparkles,
  HardDrive,
  ListChecks,
  Flag,
  Moon,
  Activity,
  Footprints,
  Trophy,
  CalendarDays,
  Download,
  User,
  FileText,
  KeyRound,
  PieChart,
  Tag,
  UserCog,
  AlertTriangle,
  Lightbulb,
  ClipboardList,
  NotebookPen,
  Link2,
  Award,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  home: Home,
  car: Car,
  "utensils-crossed": UtensilsCrossed,
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  "heart-pulse": HeartPulse,
  repeat: Repeat,
  "piggy-bank": PiggyBank,
  wallet: Wallet,
  banknote: Banknote,
  "credit-card": CreditCard,
  landmark: Landmark,
  coins: Coins,
  gift: Gift,
  plane: Plane,
  "graduation-cap": GraduationCap,
  briefcase: Briefcase,
  dumbbell: Dumbbell,
  "gamepad-2": Gamepad2,
  film: Film,
  target: Target,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "line-chart": LineChart,
  zap: Zap,
  "more-horizontal": MoreHorizontal,
  "book-open": BookOpen,
  baby: Baby,
  dog: Dog,
  wrench: Wrench,
  fuel: Fuel,
  phone: Phone,
  wifi: Wifi,
  umbrella: Umbrella,
  star: Star,
  shield: Shield,
  receipt: Receipt,
  shirt: Shirt,
  coffee: Coffee,
  pill: Pill,
  bus: Bus,
  train: Train,
  bike: Bike,
  "building-2": Building2,
  trees: Trees,
  music: Music,
  camera: Camera,
  scissors: Scissors,
  droplet: Droplet,
  flame: Flame,
  sparkles: Sparkles,
  "hard-drive": HardDrive,
  "list-checks": ListChecks,
  flag: Flag,
  moon: Moon,
  activity: Activity,
  footprints: Footprints,
  trophy: Trophy,
  "calendar-days": CalendarDays,
  download: Download,
  user: User,
  "file-text": FileText,
  key: KeyRound,
  "pie-chart": PieChart,
  tag: Tag,
  "user-cog": UserCog,
  "alert-triangle": AlertTriangle,
  lightbulb: Lightbulb,
  "clipboard-list": ClipboardList,
  "notebook-pen": NotebookPen,
  link: Link2,
  award: Award,
};

export const ICON_KEYS = Object.keys(ICONS);

export const DEFAULT_ICON = "more-horizontal";

export function getIcon(key: string): LucideIcon {
  return ICONS[key] ?? ICONS[DEFAULT_ICON];
}
